language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra

after_script:
    - cat /home/travis/build/lingochamp/QiniuImageLoader/demo/build/outputs/lint-results.xml

sudo: false